"""empty message

Revision ID: 93cfeca85b6a
Revises: 7312125460e7
Create Date: 2019-11-18 20:59:43.961194

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '93cfeca85b6a'
down_revision = '7312125460e7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('crash_data_point',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('gforce', sa.String(length=140), nullable=True),
    sa.Column('rotation', sa.String(length=140), nullable=True),
    sa.Column('classification', sa.String(length=140), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_crash_data_point_timestamp'), 'crash_data_point', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_crash_data_point_timestamp'), table_name='crash_data_point')
    op.drop_table('crash_data_point')
    # ### end Alembic commands ###
