apiVersion: apps/v1
kind: Deployment
metadata:
  name: flapi
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flapi
  template:
    metadata:
      labels:
        app: flapi
    spec:
      containers:
        - name: flapi
          image: monganai/flapi:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          env:
            - name: DD_AGENT_SERVICE_HOST
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
            - name: DD_AGENT_SERVICE_PORT
              value: "8126"
            - name: DD_AGENT_STATSD_PORT
              value: "8125"
            - name: DD_AGENT_HOST
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
---
apiVersion: v1
kind: Service
metadata:
  name: flapi
spec:
  selector:
    app: flapi
  ports:
    - name: http
      protocol: TCP
      port: 8080
  type: LoadBalancer