# datadog-agent.yaml

# Uncomment this section to use Kubernetes secrets to configure your Datadog API key

# apiVersion: v1
# kind: Secret
# metadata:
#   name: datadog-secret
#   labels:
#     app: "datadog"
# type: Opaque
# data:
#   api-key: "<YOUR_BASE64_ENCODED_API_KEY>"
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: datadog-agent
  namespace: default
spec:
  selector:
    matchLabels:
      app: datadog-agent
  template:
    metadata:
      labels:
        app: datadog-agent
      name: datadog-agent
      annotations:
        container.apparmor.security.beta.kubernetes.io/system-probe: unconfined
    
    spec:
      serviceAccountName: datadog-agent
      containers:
      
        #- image: 'datadog/agent:latest'
        #  imagePullPolicy: Always
        - image: localhost:32000/myagent:registry
          name: datadog-agent
          ports:

            - containerPort: 8125
              hostPort: 8125
              name: dogstatsdport
              protocol: UDP

            - containerPort: 8126
              hostPort: 8126
              name: traceport
              protocol: TCP
          env:
            - name: DD_API_KEY
              valueFrom:
                secretKeyRef:
                  name: datadog-secret
                  key: api-key
            - name: DD_CLUSTER_AGENT_AUTH_TOKEN
              valueFrom:
                secretKeyRef:
                  name: datadog-agent-cluster-agent
                  key: token
            - name: DD_CLUSTER_AGENT_ENABLED
              value: 'true'
            - name: DD_SITE
              value: 'datadoghq.com'
            - name: DD_TAGS
              value: "model:optiplex cluster:microk8s environment:dev internal_ip:192.168.1.24 service:agent"
            - name: DD_HOSTNAME
              value: dell-optiplex

            - name: KUBERNETES
              value: 'true'
            - name: DD_HEALTH_PORT
              value: '5555'
          #  - name: DD_COLLECT_KUBERNETES_EVENTS
          #    value: 'true'
          #  - name: DD_LEADER_ELECTION
          #    value: 'true'
            - name: DD_KUBERNETES_KUBELET_HOST
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP

            - name: DD_EXTRA_CONFIG_PROVIDERS
              value: 'clusterchecks'

            ###############
            ## DogStatsD ##
            ###############
            - name: DD_DOGSTATSD_NON_LOCAL_TRAFFIC
              value: 'true'
            - name: DD_LOG_PAYLOADS
              value: 'true'

            #########
            ## APM ##
            #########
            - name: DD_APM_ENABLED
              value: 'true'
            - name: DD_APM_NON_LOCAL_TRAFFIC
              value: 'true'
            - name: DD_APM_MAX_MEMORY
              value: '0'
            - name: DD_APM_MAX_CPU_PERCENT
              value: '0'

            ####################
            ## Log collection ##
            ####################
            - name: DD_LOGS_ENABLED
              value: 'true'
            - name: DD_LOGS_CONFIG_CONTAINER_COLLECT_ALL
              value: 'true'
            - name: DD_LOGS_CONFIG_K8S_CONTAINER_USE_FILE
              value: 'true'
            - name: DD_LOGS_CONFIG_USE_HTTP
              value: 'true'
            - name: DD_LOG_LEVEL
              value: 'TRACE'

            ########################
            ## Process collection ##
            ########################
            - name: DD_PROCESS_AGENT_ENABLED
              value: 'true'
            - name: DD_DOGSTATSD_TAG_CARDINALITY
              value: 'high'
            - name: DD_DOGSTATSD_ORIGIN_DETECTION
              value: 'true'


            - name: DD_SYSTEM_PROBE_ENABLED
              value: 'true'
            - name: DD_SYSTEM_PROBE_EXTERNAL
              value: 'true'
            - name: DD_SYSPROBE_SOCKET
              value: /var/run/s6/sysprobe.sock

          resources:
            requests:
              memory: 500Mi
              cpu: 400m
            limits:
              memory: 500Mi
              cpu: 400m

          volumeMounts:

            #######################
            ## Metric collection ##
            #######################
            - name: dockersocketdir
              mountPath: /host/var/run
            - name: procdir
              mountPath: /host/proc
              readOnly: true
            - name: cgroups
              mountPath: /host/sys/fs/cgroup
              readOnly: true

            ####################
            ## Log collection ##
            ####################
            - name: pointdir
              mountPath: /opt/datadog-agent/run
            - name: logpodpath
              mountPath: /var/log/pods

            - name: logcontainerpath
              mountPath: /var/lib/docker/containers

            ########################
            ## Process collection ##
            ########################
            - name: passwd
              mountPath: /etc/passwd
              readOnly: true

            - name: debugfs
              mountPath: /sys/kernel/debug
            - name: s6-run
              mountPath: /var/run/s6

          livenessProbe:
            httpGet:
              path: /health
              port: 5555
            initialDelaySeconds: 20
            periodSeconds: 15
            timeoutSeconds: 10
            successThreshold: 1
            failureThreshold: 3

        - name: system-probe
          image: 'datadog/agent:latest'
          imagePullPolicy: Always
          securityContext:
              capabilities:
                  add:
                      - SYS_ADMIN
                      - SYS_RESOURCE
                      - SYS_PTRACE
                      - NET_ADMIN
                      - IPC_LOCK
          command:
              - /opt/datadog-agent/embedded/bin/system-probe
          env:
              - name: DD_SYSTEM_PROBE_ENABLED
                value: 'true'
              - name: DD_SYSPROBE_SOCKET
                value: /var/run/s6/sysprobe.sock
          resources:
              requests:
                  memory: 150Mi
                  cpu: 200m
              limits:
                  memory: 150Mi
                  cpu: 200m
          volumeMounts:
              - name: procdir
                mountPath: /host/proc
                readOnly: true
              - name: cgroups
                mountPath: /host/sys/fs/cgroup
                readOnly: true
              - name: debugfs
                mountPath: /sys/kernel/debug
              - name: s6-run
                mountPath: /var/run/s6


      volumes:
        - hostPath:
            path: /var/run
          name: dockersocketdir
        - hostPath:
            path: /proc
          name: procdir
        - hostPath:
            path: /sys/fs/cgroup
          name: cgroups
        #####################
        ## Log collection  ##
        #####################
        - hostPath:
            path: /var/lib/datadog-agent/logs
          name: pointdir
        - hostPath:
            path: /var/log/pods
          name: logpodpath
        - hostPath:
            path: /var/lib/docker/containers
          name: logcontainerpath
        ########################
        ## Process collection ##
        ########################
        - hostPath:
            path: /etc/passwd
          name: passwd
        - name: s6-run
          emptyDir: {}
        - name: debugfs
          hostPath:
              path: /sys/kernel/debug