apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: redisext
spec:
  minReplicas: 1
  maxReplicas: 20
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: redis
  metrics:
  - type: External
    external:
      metricName: redis.net.commands
      metricSelector:
        matchLabels:
      targetAverageValue: 275m