apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      annotations:
        ad.datadoghq.com/redis.check_names: '["redisdb"]'
        ad.datadoghq.com/redis.init_configs: '[{}]'
        ad.datadoghq.com/redis.instances: '[{"host": "%%host%%","port":"%%port%%"}]'
        ad.datadoghq.com/redis.logs: '[{"source":"redis","service":"RideSafeAPI-REDIS"}]'
        ad.datadoghq.com/tags: '{"type": "cache","usage": "RideSafeAPI"}'
      labels:
        app: redis
        location: eu

    spec:
      containers:
        - name: redis
          image: redis:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 6379

---
apiVersion: v1
kind: Service
metadata:
  name: redis
spec:
  selector:
    app: redis
  ports:
    - port: 6379
      nodePort: 30001
  type: LoadBalancer