apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: ridesafe
spec:
  minReplicas: 1
  maxReplicas: 20
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: ridesafe
  metrics:
  - type: External
    external:
      metricName: trace.flask.request.hits
      metricSelector:
        matchLabels:
      targetAverageValue: 500