apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: ridesafe-learning
spec:
  minReplicas: 1
  maxReplicas: 4
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: ridesafe-learning
  metrics:
  - type: External
    external:
      metricName: trace.servlet.request.hits
      metricSelector:
        matchLabels:
      targetAverageValue: 550m