apiVersion: apps/v1
kind: Deployment
metadata:
  name: ridesafe
  annotations:
   ad.datadoghq.com/ridesafe.logs: '[{"source":"ridesafe","service":"ridesafe"}]'
spec:
  replicas: 3
  selector:
    matchLabels:
      app: ridesafe
  template:
    metadata:
      labels:
        app: ridesafe
    spec:
      containers:
        - name: ridesafe
          image: monganai/ridesafeapi:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: DD_ENV
              value: "dev"
            - name: DD_SERVICE
              value: "RideSafeAPI"
            - name: DD_TRACE_ANALYTICS_ENABLED
              value: "true"
            - name: DD_RUNTIME_METRICS_ENABLED
              value: "true"
            - name: DD_REDIS_ANALYTICS_ENABLED
              value: "true"
            - name: DD_INTEGRATION_ANALYTICS_ENABLED
              value: "true"
            - name: DD_AGENT_SERVICE_PORT
              value: "8126"
            - name: DD_AGENT_STATSD_PORT
              value: "8125"
            - name: DD_CLIENT_TOKEN
              value: ""
            - name: DD_APPLICATION_ID
              value: ""
            - name: DD_PROFILING_TAGS
              value: "env:dev,service:RideSafe,version:1.0"
            - name: DD_AGENT_HOST
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
---
apiVersion: v1
kind: Service
metadata:
  name: ridesafe
spec:
  selector:
    app: ridesafe
  ports:
    - name: http
      protocol: TCP
      port: 8080
      nodePort: 30000
  type: LoadBalancer