apiVersion: apps/v1
kind: Deployment
metadata:
  name: ridesafe
  labels:
    tags.datadoghq.com/env: "dev"
    tags.datadoghq.com/service: "RideSafeAPI"
    tags.datadoghq.com/version: "2.0"
spec:
  replicas: 3
  selector:
    matchLabels:
      app: ridesafe
  template:
    metadata:
      labels:
        app: ridesafe
        tags.datadoghq.com/env: "dev"
        tags.datadoghq.com/service: "RideSafeAPI"
        tags.datadoghq.com/version: "2.0"
      annotations:
        ad.datadoghq.com/ridesafe.tags: '{"lang": "python","service_port": "30000"}'
        ad.datadoghq.com/ridesafe.logs: '[{"source":"ridesafe-py","service":"RideSafeAPI"}]'
        ad.datadoghq.com/tags: '{"type": "main","usage": "RideSafeAPI"}'

    spec:
      containers:
        - name: ridesafe
          image: monganai/ridesafeapi:logz
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: DD_ENV
              value: "dev"
            - name: DD_SERVICE
              value: "RideSafeAPI"
            - name: DD_VERSION
              value: "2.0"
            - name: DD_TRACE_ANALYTICS_ENABLED
              value: "true"
            - name: DATADOG_TRACE_DEBUG
              value: "false"
            - name: DD_RUNTIME_METRICS_ENABLED
              value: "true"
            - name: DD_REDIS_ANALYTICS_ENABLED
              value: "true"
            - name: DD_INTEGRATION_ANALYTICS_ENABLED
              value: "true"
            - name: DD_CLIENT_TOKEN
              value: ""
            - name: DD_APPLICATION_ID
              value: ""
            - name: DD_AGENT_HOST
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
---
apiVersion: v1
kind: Service
metadata:
  name: ridesafe
spec:
  selector:
    app: ridesafe
  ports:
    - name: http
      protocol: TCP
      port: 8080
      nodePort: 30000
  type: LoadBalancer
